services:
  nextapp:
    container_name: bible_chatbot_nextapp
    image: nextapp:1.0.0
    build:
      context: ../bible_chatbot
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - API_URL=http://flaskapp:4000
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=true
    depends_on:
      - flaskapp

  flaskapp:
    container_name: bible_chatbot_flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:Gogi6119$@db:5432/bible_chatbot
      - API_KEY=${API_KEY}
    depends_on:
      - db

  db:
    container_name: bible_chatbot_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gogi6119$
      POSTGRES_DB: bible_chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}